---
- name: Download Cryptomator.
  get_url:
    url: "https://github.com/cryptomator/cryptomator/releases/download/{{ cryptomator_version }}/cryptomator-{{ cryptomator_version }}-x86_64.AppImage"
    dest: "{{ ansible_env.HOME }}/.local/bin/cryptomator"
    mode: "0500"
    timeout: 20
