---
- name: Generate an OpenSSH keypair
  community.crypto.openssh_keypair:
    path: "/tmp/id_{{ ssh_key_type }}"
    type: "{{ ssh_key_type }}"
    size: "{{ ssh_key_size }}"
    passphrase: "{{ ssh_key_passphrase }}"
  become: false
